import * as api from './client';
import { safetyCheck, logAudit } from './safety';

export interface ToolDef {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, { type: string; description: string; enum?: string[]; default?: unknown }>;
    required?: string[];
  };
  destructive?: boolean;
}

export interface ToolCall {
  name: string;
  arguments: Record<string, unknown>;
}

export const TOOLS: ToolDef[] = [
  { name: 'talentos_list_candidates', description: 'List candidates, optionally filtered by status or name search.', inputSchema: { type: 'object', properties: { status: { type: 'string', description: 'active, inactive, placed' }, search: { type: 'string', description: 'Name or email substring' }, limit: { type: 'number', description: 'Max results (default 20)' } } } },
  { name: 'talentos_get_candidate', description: 'Get full candidate details.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Candidate UUID' } }, required: ['id'] } },
  { name: 'talentos_list_jobs', description: 'List jobs filtered by status, company, or search.', inputSchema: { type: 'object', properties: { status: { type: 'string', description: 'active, closed, draft' }, company: { type: 'string', description: 'Company name' }, search: { type: 'string', description: 'Title/description search' }, limit: { type: 'number', description: 'Max results (default 20)' } } } },
  { name: 'talentos_get_job', description: 'Get full job details.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Job UUID' } }, required: ['id'] } },
  { name: 'talentos_list_applications', description: 'List applications by status, candidate, job, priority, or review status.', inputSchema: { type: 'object', properties: { status: { type: 'string', description: 'assigned, in_progress, applied, rejected, offer, etc.' }, candidateId: { type: 'string', description: 'Candidate UUID' }, jobId: { type: 'string', description: 'Job UUID' }, priority: { type: 'string', description: 'low, normal, high, urgent' }, reviewStatus: { type: 'string', description: 'pending, approved, changes_requested' }, limit: { type: 'number', description: 'Max results (default 20)' } } } },
  { name: 'talentos_get_application', description: 'Get full application details.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Application UUID' } }, required: ['id'] } },
  { name: 'talentos_get_readiness', description: 'Get readiness score for an application (required / matched / missing / flagged skills).', inputSchema: { type: 'object', properties: { applicationId: { type: 'string', description: 'Application UUID' } }, required: ['applicationId'] } },
  { name: 'talentos_preview_readiness', description: 'Preview readiness against arbitrary JD text.', inputSchema: { type: 'object', properties: { jdText: { type: 'string', description: 'Job description text' } }, required: ['jdText'] } },
  { name: 'talentos_get_queue_next', description: 'Get next approved application ticket for a candidate.', inputSchema: { type: 'object', properties: { candidateId: { type: 'string', description: 'Candidate UUID' } }, required: ['candidateId'] } },
  { name: 'talentos_get_adapters', description: 'Get ATS adapter manifest with versions and maturity.', inputSchema: { type: 'object', properties: {} } },
  { name: 'talentos_list_evidence', description: 'List evidence items for a candidate.', inputSchema: { type: 'object', properties: { candidateId: { type: 'string', description: 'Candidate UUID' } }, required: ['candidateId'] } },
  { name: 'talentos_list_captured_jobs', description: 'List extension-captured jobs with promotion status.', inputSchema: { type: 'object', properties: { promoted: { type: 'string', description: 'true (promoted), false (staging), or omit' }, limit: { type: 'number', description: 'Max results (default 20)' } } } },
  { name: 'talentos_create_candidate', description: 'Create a new candidate.', inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'Full name' }, email: { type: 'string', description: 'Email' }, phone: { type: 'string', description: 'Phone' }, linkedinUrl: { type: 'string', description: 'LinkedIn URL' }, location: { type: 'string', description: 'City, State' }, workAuthorization: { type: 'string', description: 'Work auth status' }, targetRoles: { type: 'string', description: 'Target roles (comma-separated)' }, notes: { type: 'string', description: 'Internal notes' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['name', 'email'] } },
  { name: 'talentos_update_candidate', description: 'Update candidate fields (partial).', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Candidate UUID' }, name: { type: 'string', description: 'Full name' }, email: { type: 'string', description: 'Email' }, status: { type: 'string', description: 'active, inactive, placed' }, notes: { type: 'string', description: 'Internal notes' }, dryRun: { type: 'boolean', description: 'Validate only' } }, required: ['id'] } },
  { name: 'talentos_create_job', description: 'Create a new job posting.', inputSchema: { type: 'object', properties: { title: { type: 'string', description: 'Job title' }, company: { type: 'string', description: 'Company' }, location: { type: 'string', description: 'Location' }, descriptionHtml: { type: 'string', description: 'Description (HTML)' }, applyUrl: { type: 'string', description: 'Apply URL' }, salaryMin: { type: 'number', description: 'Min salary' }, salaryMax: { type: 'number', description: 'Max salary' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['title', 'company'] } },
  { name: 'talentos_update_job', description: 'Update job fields (partial).', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Job UUID' }, title: { type: 'string', description: 'Job title' }, status: { type: 'string', description: 'active, closed, draft' }, location: { type: 'string', description: 'Location' }, dryRun: { type: 'boolean', description: 'Validate only' } }, required: ['id'] } },
  { name: 'talentos_create_application', description: 'Create an application linking candidate to job.', inputSchema: { type: 'object', properties: { candidateId: { type: 'string', description: 'Candidate UUID' }, jobId: { type: 'string', description: 'Job UUID (optional)' }, status: { type: 'string', description: 'Initial status (default: assigned)' }, priority: { type: 'string', description: 'low, normal, high, urgent (default: normal)' }, notes: { type: 'string', description: 'Internal notes' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['candidateId'] } },
  { name: 'talentos_update_application', description: 'Update application status, priority, review, notes, or assignment.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Application UUID' }, status: { type: 'string', description: 'assigned, in_progress, applied, replied, interview, rejected, offer' }, priority: { type: 'string', description: 'low, normal, high, urgent' }, reviewStatus: { type: 'string', description: 'pending, approved, changes_requested, not_required' }, notes: { type: 'string', description: 'Internal notes' }, reviewNote: { type: 'string', description: 'Review feedback' }, assignedTo: { type: 'string', description: 'Assign to user UUID' }, dryRun: { type: 'boolean', description: 'Validate only' } }, required: ['id'] } },
  { name: 'talentos_approve_application', description: 'Approve an application for the copilot queue (review_status=approved).', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Application UUID' }, reviewNote: { type: 'string', description: 'Approval note' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['id', 'confirm'] } },
  { name: 'talentos_add_evidence', description: 'Add evidence for a candidate (aligned with TalentOS evidence model).', inputSchema: { type: 'object', properties: { candidateId: { type: 'string', description: 'Candidate UUID' }, sourceType: { type: 'string', description: 'resume, project, certification, work_history, manual, interview' }, title: { type: 'string', description: 'Evidence title' }, description: { type: 'string', description: 'Description' }, relatedSkills: { type: 'string', description: 'Comma-separated skill names' }, proofUrl: { type: 'string', description: 'Proof URL' }, confidenceScore: { type: 'number', description: '0.0-1.0 (default: 0.7)' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['candidateId', 'sourceType', 'title', 'confirm'] } },
  { name: 'talentos_capture_job', description: 'Capture a job posting (saves to staging for human promotion).', inputSchema: { type: 'object', properties: { title: { type: 'string', description: 'Job title' }, applyUrl: { type: 'string', description: 'Apply URL' }, jdText: { type: 'string', description: 'Full JD text' }, company: { type: 'string', description: 'Company' }, location: { type: 'string', description: 'Location' }, salary: { type: 'string', description: 'Salary range' }, atsDetected: { type: 'string', description: 'greenhouse, lever, etc.' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['title', 'applyUrl', 'jdText', 'confirm'] } },
  { name: 'talentos_promote_job', description: 'Promote a captured job from staging to main jobs table.', inputSchema: { type: 'object', properties: { capturedJobId: { type: 'string', description: 'Captured job UUID' }, dryRun: { type: 'boolean', description: 'Validate only' }, confirm: { type: 'boolean', description: 'Required' } }, required: ['capturedJobId', 'confirm'] }, destructive: true },
  { name: 'talentos_delete_candidate', description: 'DELETE a candidate. Requires confirm:true.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Candidate UUID' }, confirm: { type: 'boolean', description: 'REQUIRED' }, dryRun: { type: 'boolean', description: 'Show what would be deleted' } }, required: ['id', 'confirm'] }, destructive: true },
  { name: 'talentos_delete_job', description: 'DELETE a job. Requires confirm:true.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Job UUID' }, confirm: { type: 'boolean', description: 'REQUIRED' }, dryRun: { type: 'boolean', description: 'Show what would be deleted' } }, required: ['id', 'confirm'] }, destructive: true },
  { name: 'talentos_delete_application', description: 'DELETE an application. Requires confirm:true.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Application UUID' }, confirm: { type: 'boolean', description: 'REQUIRED' }, dryRun: { type: 'boolean', description: 'Show what would be deleted' } }, required: ['id', 'confirm'] }, destructive: true },
  { name: 'talentos_delete_evidence', description: 'DELETE an evidence item. Requires confirm:true.', inputSchema: { type: 'object', properties: { id: { type: 'string', description: 'Evidence UUID' }, confirm: { type: 'boolean', description: 'REQUIRED' }, dryRun: { type: 'boolean', description: 'Show what would be deleted' } }, required: ['id', 'confirm'] }, destructive: true },
  { name: 'talentos_get_stats', description: 'Get system statistics (counts of all entities).', inputSchema: { type: 'object', properties: {} } },
  { name: 'talentos_get_debug_state', description: 'Get full in-memory debug state from mock server.', inputSchema: { type: 'object', properties: {} } },
];
